# Permalinks
permalink:           pretty

# Setup
title:               namedfork.net
tagline:             if it works, do fix it
description:         namedfork.net
url:                 https://namedfork.net
enforce_ssl:         namedfork.net
baseurl:             ''
paginate:            5
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
paginate_path:       "page:num"

# About/contact
author:
  name:              Jesús A. Álvarez
  url:               https://twitter.com/maczydeco
  email:             zydeco@namedfork.net

# Custom vars

social_links:
  - url: https://twitter.com/maczydeco
    icon: twitter
    title: Twitter
  - url: https://github.com/zydeco
    icon: github
    title: GitHub
  - url: https://instagr.am/maczydeco
    icon: instagram
    title: Instagram
  - url: https://www.youtube.com/user/maczydeco
    icon: youtube
    title: YouTube

sections:
  - id: ios
    title: iOS Software
    icon: screen-smartphone
    links:
      - title: Font Manager
        url: /fontmanager
      - title: Short Circuit
        url: /shortcircuit
  - id: mac
    title: Mac Software
    icon: mouse
  - id: misc-sw
    title: Misc Software
    icon: briefcase
    links:
      - title: see GitHub
        url: https://github.com/zydeco
      - title: openDesktop themes
        url: 'https://www.opendesktop.org/u/zydeco'

  